name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Verify patch
        run: |
          make verify-patch
      - name: Verify patch format
        run: |
          make verify-patch-format

  Test-v1-18-20-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-18-20-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.18.20-lts.1
        run: |
          make v1.18.20-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-Cmd-v1-18-20-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-18-20-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.18.20-lts.1
        run: |
          make v1.18.20-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Integration-v1-18-20-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-18-20-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.18.20-lts.1
        run: |
          make v1.18.20-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration

  e2e:
    name: run basic e2e test
    needs: Test-v1-18-20-lts-1
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_PATH: ${{ github.workspace }}/e2e-logs/
      FOCUS: .
      SKIP: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|NFS|nfs|inline.execution.and.attach|should.be.rejected.when.no.endpoints.exist
      PARALLEL: "true"
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: run e2e test 
        run: hack/local-up-cluster.sh
      # - name: upload logs to artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: e2elogs
      #     path: ${{ github.workspace }}/e2elogs/